canonifyurls = true
relativeurls = true
languageCode = "en-us"
title = "関東フライボード大会・ホバーボード大会"
theme = "hugo-terrassa-theme"
publishDir = "docs"

[Params]
logo = "./images/logo.png"

[[menu.main]]
    name = "アクアボード体験"
    weight = 6
    identifier = "about"
    url = "http://gohugo.io/"

[[menu.main]]
    name = "選手権情報"
    weight = 6
    url = "http://gohugo.io/"